### PR TITLE
bugfix(?): Write user-provided generated .gitignore content after the API-provided content

### PR DESCRIPTION
**Pull request by ulucs**
The GitignoreSync task pulls `.gitignore` data from three different sources: From the user, build process-defined `generated_content` and API-provided `gitignore_io_tokens`. This change prints `generated_content` after `gitignore_io_tokens`, allowing build setups to overwrite API-provided content (for example, adding `!Cargo.lock` to `generated_content` to allow users to commit Cargo lockfiles by overriding the API-provided Rust `.gitignore`)

### CODE REVIEW

**Comment by NiklasRosenstein** [comment]
The generated content is first because `.gitignore` applies in order from top to bottom.

```
# .gitignore
Cargo.lock
!Cargo.lock
```

Will not ignore `Cargo.lock`, wheras this will:


```
# .gitignore
!Cargo.lock
Cargo.lock
```

**Comment by NiklasRosenstein** [comment]
(Side note: The `uv-installer` job is flaky, you can ignore it failing)

**Comment by ulucs** [comment]
> The generated content is first because `.gitignore` applies in order from top to bottom.
> 
> ```
> # .gitignore
> Cargo.lock
> !Cargo.lock
> ```
> 
> Will not ignore `Cargo.lock`, wheras this will:
> 
> ```
> # .gitignore
> !Cargo.lock
> Cargo.lock
> ```

yes, currently the .gitignore sync is set up like this:

```
<build-process defined lines>
<API-provided lines>
<user-provided lines>
```

This PR changes it to 

```
<API-provided lines>
<build-process defined lines>
<user-provided lines>
```

so that the build-process can override the API-provided defaults

**Comment by ulucs** [comment]
I have edited my initial comment to be clearer on this

**Review by cdbrkfxrpt — APPROVED** [review]

**Pull request merged**
