### PR TITLE
Only check the active toolchain if rustup is installed

### PR DESCRIPTION
**Pull request by ntrinquier**

### CODE REVIEW

**Review by cdbrkfxrpt — APPROVED** [review]

**Comment by j-baker** [comment]
I don't think this is quite right. I expect the right solution for this problem is to do something like run `rustc --version` and check that the version string is a nightly release, if you want to ensure that everything runs with nightly.

It also still checks that all compilation occurs with nightly if one _does_ have rustup, I think? Whereas I think the `+nightly` will dynamically enable it for the command, so we only really want to check if nightly is _installed_, not that it's active.

If one were checkign with `rustup`, I'd expect that the right way would be to list the installed toolchains and check that nightly is in the list?

**Comment by ntrinquier** [comment]
> I don't think this is quite right. I expect the right solution for this problem is to do something like run `rustc --version` and check that the version string is a nightly release?
> 
> It also still checks that all compilation occurs with nightly, I think?

This only affects `cargo fmt`, not the compilation (and now that we made it opt-out, only the user specified `nightly=True`)

**Comment by j-baker** [comment]
Won't `rustup show active-toolchain` return nightly if rustc is going to compile with nightly? Or am I misunderstanding what that command returns?

**Comment by ntrinquier** [comment]
> I think the +nightly will dynamically enable it for the command, so we only really want to check if nightly is installed, not that it's active.

yeah that's fair

**Review by cdbrkfxrpt — APPROVED** [review]

**Pull request merged**
